spring:
  datasource.driverClassName: org.postgresql.Driver
  mail.host: mx.freenet.de
  jpa.hibernate.ddlAuto: validate

server.openRedirectionPublicPort: false

application:
  applicationUrl: https://connection-koeln.herokuapp.com/ui
  allowedOrigins: https://connection-koeln.herokuapp.com
  mail:
    from: Connection Köln e.V. <info@connection.koeln>
    sender: Connection Köln e.V.